# Generated by Django 3.1.3 on 2020-11-29 22:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c19trace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userplace',
            options={'ordering': ('place__name',), 'verbose_name': 'User place', 'verbose_name_plural': 'User places'},
        ),
        migrations.AlterField(
            model_name='entrypoint',
            name='type',
            field=models.CharField(choices=[('agua', 'water'), ('aire', 'air'), ('tierra', 'Land')], help_text='options:\nagua: agua\naire: aire\ntierra: tierra', max_length=64, verbose_name='Transportation mode'),
        ),
        migrations.AlterField(
            model_name='person',
            name='contact_relationship',
            field=models.CharField(choices=[('abuelo/a', 'Grandparent'), ('amigo/a', 'Friend'), ('colega', 'Colegue'), ('cuñado/a', 'Sibling in law'), ('hermano/a', 'sibling'), ('hijo/a', 'Child'), ('nieto/a', 'Grandchild'), ('padre/madre', 'Parent'), ('primo/a', 'Cousin'), ('sobrino/a', 'Nephew'), ('suegro/a', 'Parent in law'), ('tio/a', 'Uncle/aunt')], help_text='options:\nabuelo/a: Abuela/o\namigo/a: Amiga/o\ncolega: Colega\ncuñado/a: Cuñada/o\nhermano/a: hermanoa/o\nhijo/a: Hija/o\nnieto/a: Nieta/o\npadre/madre: Madre/Padre\nprimo/a: Prima/o\nsobrino/a: Sobrina/o\nsuegro/a: Suegra/o\ntio/a: Tía/Tío\n* Tambien puede ser llenado con una entrada personalizada', max_length=24, verbose_name='Contact replationship'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Male'), ('Femenino', 'Female'), ('Otro', 'Other')], help_text='options:\nMasculino: Masculino\nFemenino: Femenino\nOtro: Otro', max_length=24, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='person',
            name='main_transportation_mean',
            field=models.CharField(choices=[('Motocicleta', 'Motorcycle'), ('Bicicleta', 'Bycicle'), ('Auto/Jeep/Camioneta', 'Car/Jeep/Pickup truck'), ('Motorhome/Casa Rodante', 'Motorhome'), ('Bus', 'Bus'), ('Camión', 'Truck')], help_text='options:\nMotocicleta: Moto\nBicicleta: Bicicleta\nAuto/Jeep/Camioneta: Automóvil/Jeep/Camioneta\nMotorhome/Casa Rodante: Casa rodante/Motorhome\nBus: Bus\nCamión: Camion\n* Tambien puede ser llenado con una entrada personalizada', max_length=64, verbose_name='Main transportation mean'),
        ),
        migrations.AlterField(
            model_name='person',
            name='residence',
            field=models.CharField(choices=[('Chile', 'Chile'), ('extranjero', 'Not Chile')], help_text='options:\nChile: Chile\nextranjero: Extranjero', max_length=24, verbose_name='Residence place'),
        ),
        migrations.AlterField(
            model_name='person',
            name='transportation_mode',
            field=models.CharField(choices=[('agua', 'water'), ('aire', 'air'), ('tierra', 'Land')], help_text='options:\nagua: agua\naire: aire\ntierra: tierra', max_length=8, verbose_name='Transportation mode'),
        ),
        migrations.AlterField(
            model_name='person',
            name='travel_document',
            field=models.CharField(choices=[('RUN', 'RUN'), ('pasaporte', 'Passport'), ('otro', 'Other')], help_text='options:\nRUN: RUN\npasaporte: Pasaporte\notro: Otro', max_length=16, verbose_name='Travel document'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.IntegerField(choices=[(1, 'Turistic service'), (2, 'Turist attraction'), (3, 'Turistic information office'), (4, 'Health place'), (5, 'Check point municipal'), (6, 'Sanitary check point '), (7, 'Border crossing')], help_text='options:\n1: Servicio turístico\n2: Atracción turística\n3: Oficina de información turística\n4: Posta rural\n5: Punto de control municipal\n6: Sanitary check point \n7: Punto fronterizo', verbose_name='Place type'),
        ),
        migrations.AlterField(
            model_name='underageperson',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Male'), ('Femenino', 'Female'), ('Otro', 'Other')], help_text='options:\nMasculino: Masculino\nFemenino: Femenino\nOtro: Otro', max_length=24, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='underageperson',
            name='relationship',
            field=models.CharField(choices=[('amigo/a', 'Friend'), ('colega', 'Colegue'), ('cuñado/a', 'Sibling in law'), ('hermano/a', 'sibling'), ('hijo/a', 'Child'), ('nieto/a', 'Grandchild'), ('primo/a', 'Cousin'), ('sobrino/a', 'Nephew')], help_text='options:\namigo/a: Amiga/o\ncolega: Colega\ncuñado/a: Cuñada/o\nhermano/a: hermanoa/o\nhijo/a: Hija/o\nnieto/a: Nieta/o\nprimo/a: Prima/o\nsobrino/a: Sobrina/o\n* Tambien puede ser llenado con una entrada personalizada', max_length=24, verbose_name='Contact replationship'),
        ),
        migrations.CreateModel(
            name='PlaceCheckPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96, verbose_name='Nombre')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='c19trace.place', verbose_name='Place entity')),
            ],
            options={
                'verbose_name': 'Place check point',
                'verbose_name_plural': 'Place check points',
                'db_table': 'c19t_place_check_point',
                'ordering': ('name',),
            },
        ),
    ]
