# Generated by Django 3.1.3 on 2020-11-30 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('c19trace', '0002_initial_rev_01'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPlace',
            new_name='PlaceUser',
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('name',), 'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
        migrations.AlterModelOptions(
            name='placeuser',
            options={'ordering': ('place__name',), 'verbose_name': 'Place user', 'verbose_name_plural': 'Place users'},
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.IntegerField(choices=[(1, 'Turistic service'), (2, 'Turist attraction'), (3, 'Turistic information office'), (4, 'Health place'), (5, 'Check point municipal'), (6, 'Sanitary check point'), (7, 'Border crossing')], help_text='options:\n1: Servicio turístico\n2: Atracción turística\n3: Oficina de información turística\n4: Posta rural\n5: Punto de control municipal\n6: Sanitary check point\n7: Punto fronterizo', verbose_name='Place type'),
        ),
        migrations.AlterField(
            model_name='placecheckpoint',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='c19trace.place', verbose_name='Place'),
        ),
        migrations.AlterModelTable(
            name='placeuser',
            table='c19t_place_users',
        ),
    ]
