# Generated by Django 3.1.3 on 2020-12-06 21:13

import apps.c19trace.models.util
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('c19trace', '0004_initial_rev_03'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='person',
            name='residence_chile_comuna',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Residence in Chile: Comuna'),
        ),
        migrations.AlterField(
            model_name='person',
            name='residence_chile_region',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Residence in Chile: Region'),
        ),
        migrations.AlterField(
            model_name='person',
            name='residence_other_country',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Residence outside Chile: Country'),
        ),
        migrations.AlterField(
            model_name='person',
            name='residence_other_place',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Residence outside Chile: Place'),
        ),
        migrations.CreateModel(
            name='PasswordChangeOrCreate',
            fields=[
                ('id', models.CharField(default=apps.c19trace.models.util.password_request_id, max_length=64, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=apps.c19trace.models.util.password_request_key, max_length=64, verbose_name='Key')),
                ('expires', models.DateTimeField(default=apps.c19trace.models.util.password_request_expiracy, verbose_name='Expires')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='c19trace.person', verbose_name='Person')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Password request',
                'verbose_name_plural': 'Password requests',
                'db_table': 'c19t_password_change_or_create',
                'ordering': ('-expires', 'user'),
            },
        ),
    ]
