# Generated by Django 3.1.3 on 2020-12-07 03:29

import apps.c19trace.models.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c19trace', '0005_initial_rev_04'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordchangeorcreate',
            name='key',
            field=models.CharField(default=apps.c19trace.models.util.password_request_key, max_length=128, verbose_name='Key'),
        ),
    ]
