# Generated by Django 3.1.3 on 2020-12-09 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c19trace', '0006_initial_rev_05'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='service_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='c19trace.turisticserviceclass', verbose_name='Service class'),
            preserve_default=False,
        ),
    ]
