# Generated by Django 3.1.3 on 2020-12-09 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c19trace', '0007_initial_rev_06'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placecheckpoint',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_points', to='c19trace.place', verbose_name='Place'),
        ),
        migrations.AlterModelTable(
            name='place',
            table='c19t_places',
        ),
    ]
