# Generated by Django 3.1.3 on 2020-12-23 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c19trace', '0010_user_extra_conf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placepersonchecksymptom',
            options={'verbose_name': 'Place person check symptoms', 'verbose_name_plural': 'Place persons checks symptoms'},
        ),
        migrations.AddField(
            model_name='placepersonchecksymptom',
            name='temperature',
            field=models.IntegerField(default=46, verbose_name='Temperature'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='contact_relationship',
            field=models.CharField(choices=[('familiar/amigo', 'Family/Friend'), ('travel agency', 'Travel Agency'), ('tour operator', 'Tour Operator'), ('empresa (negocios o trabajo)', 'Company (Business or Work)'), ('ninguno', 'None')], help_text='Opciones:\n- familiar/amigo: Family/Friend\n- travel agency: Agencia de viajes\n- tour operator: Operador de tour\n- empresa (negocios o trabajo): Empresa (Negocios or trabajo)\n- ninguno: Ninguno\n* Tambien puede ser llenado con una entrada personalizada', max_length=48, verbose_name='Contact replationship'),
        ),
        migrations.AlterField(
            model_name='placepersoncheck',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons_checks', to='c19trace.person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='userextraconf',
            name='traceability',
            field=models.BooleanField(default=False, verbose_name='Traceability'),
        ),
        migrations.AlterModelTable(
            name='placepersonchecksymptom',
            table='c19t_place_persons_checks_symptoms',
        ),
    ]
