# Generated by Django 3.1.3 on 2021-01-12 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c19trace', '0013_revision_03'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(help_text='Opciones:\n- masculino: Masculino\n- femenino: Femenino\n- otro: Otro', max_length=24, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_surname',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='Last surname'),
        ),
        migrations.AlterField(
            model_name='person',
            name='visit_subject',
            field=models.CharField(blank=True, choices=[('turismo', 'Turism'), ('vacaciones', 'Vacations'), ('visita familiares/amigos', 'Visit to family or friend'), ('trabajo', 'Work'), ('negocios', 'Business'), ('otro', 'Other')], max_length=128, null=True, verbose_name='Visit subject'),
        ),
        migrations.AlterField(
            model_name='placepersoncheck',
            name='is_customer',
            field=models.BooleanField(default=False, verbose_name='Is customer'),
        ),
        migrations.AlterField(
            model_name='placepersoncheck',
            name='is_employee',
            field=models.BooleanField(default=False, verbose_name='Is employee'),
        ),
        migrations.AlterField(
            model_name='placepersoncheck',
            name='is_provider',
            field=models.BooleanField(default=False, verbose_name='Is provider'),
        ),
        migrations.AlterField(
            model_name='placepersoncheck',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_checks', to='c19trace.person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='placepersoncheck',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_checks', to='c19trace.place', verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='underageperson',
            name='gender',
            field=models.CharField(help_text='Opciones:\n- masculino: Masculino\n- femenino: Femenino\n- otro: Otro', max_length=24, verbose_name='Gender'),
        ),
    ]
